function [trainedClassifier, validationAccuracy] = trainSVMClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy as a
%       percentage. In the app, the Models pane displays this overall
%       accuracy score for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 02-Sep-2024 09:35:16


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Fz-FC3-mean', 'Fz-FC3-std', 'Fz-FC3-variance', 'Fz-FC1-mean', 'Fz-FC1-std', 'Fz-FC1-variance', 'Fz-FCz-mean', 'Fz-FCz-std', 'Fz-FCz-variance', 'Fz-FC2-mean', 'Fz-FC2-std', 'Fz-FC2-variance', 'Fz-FC4-mean', 'Fz-FC4-std', 'Fz-FC4-variance', 'Fz-C3-mean', 'Fz-C3-std', 'Fz-C3-variance', 'Fz-C1-mean', 'Fz-C1-std', 'Fz-C1-variance', 'Fz-C2-mean', 'Fz-C2-std', 'Fz-C2-variance', 'Fz-C4-mean', 'Fz-C4-std', 'Fz-C4-variance', 'Fz-CP3-mean', 'Fz-CP3-std', 'Fz-CP3-variance', 'Fz-CP1-mean', 'Fz-CP1-std', 'Fz-CP1-variance', 'Fz-CPz-mean', 'Fz-CPz-std', 'Fz-CPz-variance', 'Fz-CP2-mean', 'Fz-CP2-std', 'Fz-CP2-variance', 'Fz-CP4-mean', 'Fz-CP4-std', 'Fz-CP4-variance', 'FC3-FC1-mean', 'FC3-FC1-std', 'FC3-FC1-variance', 'FC3-FCz-mean', 'FC3-FCz-std', 'FC3-FCz-variance', 'FC3-FC2-mean', 'FC3-FC2-std', 'FC3-FC2-variance', 'FC3-FC4-mean', 'FC3-FC4-std', 'FC3-FC4-variance', 'FC3-C3-mean', 'FC3-C3-std', 'FC3-C3-variance', 'FC3-C1-mean', 'FC3-C1-std', 'FC3-C1-variance', 'FC3-C2-mean', 'FC3-C2-std', 'FC3-C2-variance', 'FC3-C4-mean', 'FC3-C4-std', 'FC3-C4-variance', 'FC3-CP3-mean', 'FC3-CP3-std', 'FC3-CP3-variance', 'FC3-CP1-mean', 'FC3-CP1-std', 'FC3-CP1-variance', 'FC3-CPz-mean', 'FC3-CPz-std', 'FC3-CPz-variance', 'FC3-CP2-mean', 'FC3-CP2-std', 'FC3-CP2-variance', 'FC3-CP4-mean', 'FC3-CP4-std', 'FC3-CP4-variance', 'FC1-FCz-mean', 'FC1-FCz-std', 'FC1-FCz-variance', 'FC1-FC2-mean', 'FC1-FC2-std', 'FC1-FC2-variance', 'FC1-FC4-mean', 'FC1-FC4-std', 'FC1-FC4-variance', 'FC1-C3-mean', 'FC1-C3-std', 'FC1-C3-variance', 'FC1-C1-mean', 'FC1-C1-std', 'FC1-C1-variance', 'FC1-C2-mean', 'FC1-C2-std', 'FC1-C2-variance', 'FC1-C4-mean', 'FC1-C4-std', 'FC1-C4-variance', 'FC1-CP3-mean', 'FC1-CP3-std', 'FC1-CP3-variance', 'FC1-CP1-mean', 'FC1-CP1-std', 'FC1-CP1-variance', 'FC1-CPz-mean', 'FC1-CPz-std', 'FC1-CPz-variance', 'FC1-CP2-mean', 'FC1-CP2-std', 'FC1-CP2-variance', 'FC1-CP4-mean', 'FC1-CP4-std', 'FC1-CP4-variance', 'FCz-FC2-mean', 'FCz-FC2-std', 'FCz-FC2-variance', 'FCz-FC4-mean', 'FCz-FC4-std', 'FCz-FC4-variance', 'FCz-C3-mean', 'FCz-C3-std', 'FCz-C3-variance', 'FCz-C1-mean', 'FCz-C1-std', 'FCz-C1-variance', 'FCz-C2-mean', 'FCz-C2-std', 'FCz-C2-variance', 'FCz-C4-mean', 'FCz-C4-std', 'FCz-C4-variance', 'FCz-CP3-mean', 'FCz-CP3-std', 'FCz-CP3-variance', 'FCz-CP1-mean', 'FCz-CP1-std', 'FCz-CP1-variance', 'FCz-CPz-mean', 'FCz-CPz-std', 'FCz-CPz-variance', 'FCz-CP2-mean', 'FCz-CP2-std', 'FCz-CP2-variance', 'FCz-CP4-mean', 'FCz-CP4-std', 'FCz-CP4-variance', 'FC2-FC4-mean', 'FC2-FC4-std', 'FC2-FC4-variance', 'FC2-C3-mean', 'FC2-C3-std', 'FC2-C3-variance', 'FC2-C1-mean', 'FC2-C1-std', 'FC2-C1-variance', 'FC2-C2-mean', 'FC2-C2-std', 'FC2-C2-variance', 'FC2-C4-mean', 'FC2-C4-std', 'FC2-C4-variance', 'FC2-CP3-mean', 'FC2-CP3-std', 'FC2-CP3-variance', 'FC2-CP1-mean', 'FC2-CP1-std', 'FC2-CP1-variance', 'FC2-CPz-mean', 'FC2-CPz-std', 'FC2-CPz-variance', 'FC2-CP2-mean', 'FC2-CP2-std', 'FC2-CP2-variance', 'FC2-CP4-mean', 'FC2-CP4-std', 'FC2-CP4-variance', 'FC4-C3-mean', 'FC4-C3-std', 'FC4-C3-variance', 'FC4-C1-mean', 'FC4-C1-std', 'FC4-C1-variance', 'FC4-C2-mean', 'FC4-C2-std', 'FC4-C2-variance', 'FC4-C4-mean', 'FC4-C4-std', 'FC4-C4-variance', 'FC4-CP3-mean', 'FC4-CP3-std', 'FC4-CP3-variance', 'FC4-CP1-mean', 'FC4-CP1-std', 'FC4-CP1-variance', 'FC4-CPz-mean', 'FC4-CPz-std', 'FC4-CPz-variance', 'FC4-CP2-mean', 'FC4-CP2-std', 'FC4-CP2-variance', 'FC4-CP4-mean', 'FC4-CP4-std', 'FC4-CP4-variance', 'C3-C1-mean', 'C3-C1-std', 'C3-C1-variance', 'C3-C2-mean', 'C3-C2-std', 'C3-C2-variance', 'C3-C4-mean', 'C3-C4-std', 'C3-C4-variance', 'C3-CP3-mean', 'C3-CP3-std', 'C3-CP3-variance', 'C3-CP1-mean', 'C3-CP1-std', 'C3-CP1-variance', 'C3-CPz-mean', 'C3-CPz-std', 'C3-CPz-variance', 'C3-CP2-mean', 'C3-CP2-std', 'C3-CP2-variance', 'C3-CP4-mean', 'C3-CP4-std', 'C3-CP4-variance', 'C1-C2-mean', 'C1-C2-std', 'C1-C2-variance', 'C1-C4-mean', 'C1-C4-std', 'C1-C4-variance', 'C1-CP3-mean', 'C1-CP3-std', 'C1-CP3-variance', 'C1-CP1-mean', 'C1-CP1-std', 'C1-CP1-variance', 'C1-CPz-mean', 'C1-CPz-std', 'C1-CPz-variance', 'C1-CP2-mean', 'C1-CP2-std', 'C1-CP2-variance', 'C1-CP4-mean', 'C1-CP4-std', 'C1-CP4-variance', 'C2-C4-mean', 'C2-C4-std', 'C2-C4-variance', 'C2-CP3-mean', 'C2-CP3-std', 'C2-CP3-variance', 'C2-CP1-mean', 'C2-CP1-std', 'C2-CP1-variance', 'C2-CPz-mean', 'C2-CPz-std', 'C2-CPz-variance', 'C2-CP2-mean', 'C2-CP2-std', 'C2-CP2-variance', 'C2-CP4-mean', 'C2-CP4-std', 'C2-CP4-variance', 'C4-CP3-mean', 'C4-CP3-std', 'C4-CP3-variance', 'C4-CP1-mean', 'C4-CP1-std', 'C4-CP1-variance', 'C4-CPz-mean', 'C4-CPz-std', 'C4-CPz-variance', 'C4-CP2-mean', 'C4-CP2-std', 'C4-CP2-variance', 'C4-CP4-mean', 'C4-CP4-std', 'C4-CP4-variance', 'CP3-CP1-mean', 'CP3-CP1-std', 'CP3-CP1-variance', 'CP3-CPz-mean', 'CP3-CPz-std', 'CP3-CPz-variance', 'CP3-CP2-mean', 'CP3-CP2-std', 'CP3-CP2-variance', 'CP3-CP4-mean', 'CP3-CP4-std', 'CP3-CP4-variance', 'CP1-CPz-mean', 'CP1-CPz-std', 'CP1-CPz-variance', 'CP1-CP2-mean', 'CP1-CP2-std', 'CP1-CP2-variance', 'CP1-CP4-mean', 'CP1-CP4-std', 'CP1-CP4-variance', 'CPz-CP2-mean', 'CPz-CP2-std', 'CPz-CP2-variance', 'CPz-CP4-mean', 'CPz-CP4-std', 'CPz-CP4-variance', 'CP2-CP4-mean', 'CP2-CP4-std', 'CP2-CP4-variance', 'Fz-FC3', 'Fz-FC1', 'Fz-FCz', 'Fz-FC2', 'Fz-FC4', 'Fz-C3', 'Fz-C1', 'Fz-C2', 'Fz-C4', 'Fz-CP3', 'Fz-CP1', 'Fz-CPz', 'Fz-CP2', 'Fz-CP4', 'FC3-FC1', 'FC3-FCz', 'FC3-FC2', 'FC3-FC4', 'FC3-C3', 'FC3-C1', 'FC3-C2', 'FC3-C4', 'FC3-CP3', 'FC3-CP1', 'FC3-CPz', 'FC3-CP2', 'FC3-CP4', 'FC1-FCz', 'FC1-FC2', 'FC1-FC4', 'FC1-C3', 'FC1-C1', 'FC1-C2', 'FC1-C4', 'FC1-CP3', 'FC1-CP1', 'FC1-CPz', 'FC1-CP2', 'FC1-CP4', 'FCz-FC2', 'FCz-FC4', 'FCz-C3', 'FCz-C1', 'FCz-C2', 'FCz-C4', 'FCz-CP3', 'FCz-CP1', 'FCz-CPz', 'FCz-CP2', 'FCz-CP4', 'FC2-FC4', 'FC2-C3', 'FC2-C1', 'FC2-C2', 'FC2-C4', 'FC2-CP3', 'FC2-CP1', 'FC2-CPz', 'FC2-CP2', 'FC2-CP4', 'FC4-C3', 'FC4-C1', 'FC4-C2', 'FC4-C4', 'FC4-CP3', 'FC4-CP1', 'FC4-CPz', 'FC4-CP2', 'FC4-CP4', 'C3-C1', 'C3-C2', 'C3-C4', 'C3-CP3', 'C3-CP1', 'C3-CPz', 'C3-CP2', 'C3-CP4', 'C1-C2', 'C1-C4', 'C1-CP3', 'C1-CP1', 'C1-CPz', 'C1-CP2', 'C1-CP4', 'C2-C4', 'C2-CP3', 'C2-CP1', 'C2-CPz', 'C2-CP2', 'C2-CP4', 'C4-CP3', 'C4-CP1', 'C4-CPz', 'C4-CP2', 'C4-CP4', 'CP3-CP1', 'CP3-CPz', 'CP3-CP2', 'CP3-CP4', 'CP1-CPz', 'CP1-CP2', 'CP1-CP4', 'CPz-CP2', 'CPz-CP4', 'CP2-CP4'};
predictors = inputTable(:, predictorNames);
response = inputTable.Class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Feature Ranking and Selection
% Replace Inf/-Inf values with NaN to prepare data for normalization
predictors = standardizeMissing(predictors, {Inf, -Inf});
% Normalize data for feature ranking
predictorMatrix = normalize(predictors, "DataVariable", ~isCategoricalPredictor);
newPredictorMatrix = zeros(size(predictorMatrix));
for i = 1:size(predictorMatrix, 2)
    if isCategoricalPredictor(i)
        newPredictorMatrix(:,i) = grp2idx(predictorMatrix{:,i});
    else
        newPredictorMatrix(:,i) = predictorMatrix{:,i};
    end
end
predictorMatrix = newPredictorMatrix;
responseVector = grp2idx(response);

% Rank features using ANOVA algorithm
for i = 1:size(predictorMatrix, 2)
    pValues(i) = anova1(...
        predictorMatrix(:,i), ...
        responseVector, ...
        'off');
end
[~,featureIndex] = sort(-log(pValues), 'descend');
numFeaturesToKeep = 50;
includedPredictorNames = predictors.Properties.VariableNames(featureIndex(1:numFeaturesToKeep));
predictors = predictors(:,includedPredictorNames);
isCategoricalPredictor = isCategoricalPredictor(featureIndex(1:numFeaturesToKeep));

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationKNN = fitcknn(...
    predictors, ...
    response, ...
    'Distance', 'Cityblock', ...
    'Exponent', [], ...
    'NumNeighbors', 65, ...
    'DistanceWeight', 'Inverse', ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
featureSelectionFcn = @(x) x(:,includedPredictorNames);
knnPredictFcn = @(x) predict(classificationKNN, x);
trainedClassifier.predictFcn = @(x) knnPredictFcn(featureSelectionFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'C1-C2', 'C1-C2-mean', 'C1-C2-std', 'C1-C2-variance', 'C1-C4', 'C1-C4-mean', 'C1-C4-std', 'C1-C4-variance', 'C1-CP1', 'C1-CP1-mean', 'C1-CP1-std', 'C1-CP1-variance', 'C1-CP2', 'C1-CP2-mean', 'C1-CP2-std', 'C1-CP2-variance', 'C1-CP3', 'C1-CP3-mean', 'C1-CP3-std', 'C1-CP3-variance', 'C1-CP4', 'C1-CP4-mean', 'C1-CP4-std', 'C1-CP4-variance', 'C1-CPz', 'C1-CPz-mean', 'C1-CPz-std', 'C1-CPz-variance', 'C2-C4', 'C2-C4-mean', 'C2-C4-std', 'C2-C4-variance', 'C2-CP1', 'C2-CP1-mean', 'C2-CP1-std', 'C2-CP1-variance', 'C2-CP2', 'C2-CP2-mean', 'C2-CP2-std', 'C2-CP2-variance', 'C2-CP3', 'C2-CP3-mean', 'C2-CP3-std', 'C2-CP3-variance', 'C2-CP4', 'C2-CP4-mean', 'C2-CP4-std', 'C2-CP4-variance', 'C2-CPz', 'C2-CPz-mean', 'C2-CPz-std', 'C2-CPz-variance', 'C3-C1', 'C3-C1-mean', 'C3-C1-std', 'C3-C1-variance', 'C3-C2', 'C3-C2-mean', 'C3-C2-std', 'C3-C2-variance', 'C3-C4', 'C3-C4-mean', 'C3-C4-std', 'C3-C4-variance', 'C3-CP1', 'C3-CP1-mean', 'C3-CP1-std', 'C3-CP1-variance', 'C3-CP2', 'C3-CP2-mean', 'C3-CP2-std', 'C3-CP2-variance', 'C3-CP3', 'C3-CP3-mean', 'C3-CP3-std', 'C3-CP3-variance', 'C3-CP4', 'C3-CP4-mean', 'C3-CP4-std', 'C3-CP4-variance', 'C3-CPz', 'C3-CPz-mean', 'C3-CPz-std', 'C3-CPz-variance', 'C4-CP1', 'C4-CP1-mean', 'C4-CP1-std', 'C4-CP1-variance', 'C4-CP2', 'C4-CP2-mean', 'C4-CP2-std', 'C4-CP2-variance', 'C4-CP3', 'C4-CP3-mean', 'C4-CP3-std', 'C4-CP3-variance', 'C4-CP4', 'C4-CP4-mean', 'C4-CP4-std', 'C4-CP4-variance', 'C4-CPz', 'C4-CPz-mean', 'C4-CPz-std', 'C4-CPz-variance', 'CP1-CP2', 'CP1-CP2-mean', 'CP1-CP2-std', 'CP1-CP2-variance', 'CP1-CP4', 'CP1-CP4-mean', 'CP1-CP4-std', 'CP1-CP4-variance', 'CP1-CPz', 'CP1-CPz-mean', 'CP1-CPz-std', 'CP1-CPz-variance', 'CP2-CP4', 'CP2-CP4-mean', 'CP2-CP4-std', 'CP2-CP4-variance', 'CP3-CP1', 'CP3-CP1-mean', 'CP3-CP1-std', 'CP3-CP1-variance', 'CP3-CP2', 'CP3-CP2-mean', 'CP3-CP2-std', 'CP3-CP2-variance', 'CP3-CP4', 'CP3-CP4-mean', 'CP3-CP4-std', 'CP3-CP4-variance', 'CP3-CPz', 'CP3-CPz-mean', 'CP3-CPz-std', 'CP3-CPz-variance', 'CPz-CP2', 'CPz-CP2-mean', 'CPz-CP2-std', 'CPz-CP2-variance', 'CPz-CP4', 'CPz-CP4-mean', 'CPz-CP4-std', 'CPz-CP4-variance', 'FC1-C1', 'FC1-C1-mean', 'FC1-C1-std', 'FC1-C1-variance', 'FC1-C2', 'FC1-C2-mean', 'FC1-C2-std', 'FC1-C2-variance', 'FC1-C3', 'FC1-C3-mean', 'FC1-C3-std', 'FC1-C3-variance', 'FC1-C4', 'FC1-C4-mean', 'FC1-C4-std', 'FC1-C4-variance', 'FC1-CP1', 'FC1-CP1-mean', 'FC1-CP1-std', 'FC1-CP1-variance', 'FC1-CP2', 'FC1-CP2-mean', 'FC1-CP2-std', 'FC1-CP2-variance', 'FC1-CP3', 'FC1-CP3-mean', 'FC1-CP3-std', 'FC1-CP3-variance', 'FC1-CP4', 'FC1-CP4-mean', 'FC1-CP4-std', 'FC1-CP4-variance', 'FC1-CPz', 'FC1-CPz-mean', 'FC1-CPz-std', 'FC1-CPz-variance', 'FC1-FC2', 'FC1-FC2-mean', 'FC1-FC2-std', 'FC1-FC2-variance', 'FC1-FC4', 'FC1-FC4-mean', 'FC1-FC4-std', 'FC1-FC4-variance', 'FC1-FCz', 'FC1-FCz-mean', 'FC1-FCz-std', 'FC1-FCz-variance', 'FC2-C1', 'FC2-C1-mean', 'FC2-C1-std', 'FC2-C1-variance', 'FC2-C2', 'FC2-C2-mean', 'FC2-C2-std', 'FC2-C2-variance', 'FC2-C3', 'FC2-C3-mean', 'FC2-C3-std', 'FC2-C3-variance', 'FC2-C4', 'FC2-C4-mean', 'FC2-C4-std', 'FC2-C4-variance', 'FC2-CP1', 'FC2-CP1-mean', 'FC2-CP1-std', 'FC2-CP1-variance', 'FC2-CP2', 'FC2-CP2-mean', 'FC2-CP2-std', 'FC2-CP2-variance', 'FC2-CP3', 'FC2-CP3-mean', 'FC2-CP3-std', 'FC2-CP3-variance', 'FC2-CP4', 'FC2-CP4-mean', 'FC2-CP4-std', 'FC2-CP4-variance', 'FC2-CPz', 'FC2-CPz-mean', 'FC2-CPz-std', 'FC2-CPz-variance', 'FC2-FC4', 'FC2-FC4-mean', 'FC2-FC4-std', 'FC2-FC4-variance', 'FC3-C1', 'FC3-C1-mean', 'FC3-C1-std', 'FC3-C1-variance', 'FC3-C2', 'FC3-C2-mean', 'FC3-C2-std', 'FC3-C2-variance', 'FC3-C3', 'FC3-C3-mean', 'FC3-C3-std', 'FC3-C3-variance', 'FC3-C4', 'FC3-C4-mean', 'FC3-C4-std', 'FC3-C4-variance', 'FC3-CP1', 'FC3-CP1-mean', 'FC3-CP1-std', 'FC3-CP1-variance', 'FC3-CP2', 'FC3-CP2-mean', 'FC3-CP2-std', 'FC3-CP2-variance', 'FC3-CP3', 'FC3-CP3-mean', 'FC3-CP3-std', 'FC3-CP3-variance', 'FC3-CP4', 'FC3-CP4-mean', 'FC3-CP4-std', 'FC3-CP4-variance', 'FC3-CPz', 'FC3-CPz-mean', 'FC3-CPz-std', 'FC3-CPz-variance', 'FC3-FC1', 'FC3-FC1-mean', 'FC3-FC1-std', 'FC3-FC1-variance', 'FC3-FC2', 'FC3-FC2-mean', 'FC3-FC2-std', 'FC3-FC2-variance', 'FC3-FC4', 'FC3-FC4-mean', 'FC3-FC4-std', 'FC3-FC4-variance', 'FC3-FCz', 'FC3-FCz-mean', 'FC3-FCz-std', 'FC3-FCz-variance', 'FC4-C1', 'FC4-C1-mean', 'FC4-C1-std', 'FC4-C1-variance', 'FC4-C2', 'FC4-C2-mean', 'FC4-C2-std', 'FC4-C2-variance', 'FC4-C3', 'FC4-C3-mean', 'FC4-C3-std', 'FC4-C3-variance', 'FC4-C4', 'FC4-C4-mean', 'FC4-C4-std', 'FC4-C4-variance', 'FC4-CP1', 'FC4-CP1-mean', 'FC4-CP1-std', 'FC4-CP1-variance', 'FC4-CP2', 'FC4-CP2-mean', 'FC4-CP2-std', 'FC4-CP2-variance', 'FC4-CP3', 'FC4-CP3-mean', 'FC4-CP3-std', 'FC4-CP3-variance', 'FC4-CP4', 'FC4-CP4-mean', 'FC4-CP4-std', 'FC4-CP4-variance', 'FC4-CPz', 'FC4-CPz-mean', 'FC4-CPz-std', 'FC4-CPz-variance', 'FCz-C1', 'FCz-C1-mean', 'FCz-C1-std', 'FCz-C1-variance', 'FCz-C2', 'FCz-C2-mean', 'FCz-C2-std', 'FCz-C2-variance', 'FCz-C3', 'FCz-C3-mean', 'FCz-C3-std', 'FCz-C3-variance', 'FCz-C4', 'FCz-C4-mean', 'FCz-C4-std', 'FCz-C4-variance', 'FCz-CP1', 'FCz-CP1-mean', 'FCz-CP1-std', 'FCz-CP1-variance', 'FCz-CP2', 'FCz-CP2-mean', 'FCz-CP2-std', 'FCz-CP2-variance', 'FCz-CP3', 'FCz-CP3-mean', 'FCz-CP3-std', 'FCz-CP3-variance', 'FCz-CP4', 'FCz-CP4-mean', 'FCz-CP4-std', 'FCz-CP4-variance', 'FCz-CPz', 'FCz-CPz-mean', 'FCz-CPz-std', 'FCz-CPz-variance', 'FCz-FC2', 'FCz-FC2-mean', 'FCz-FC2-std', 'FCz-FC2-variance', 'FCz-FC4', 'FCz-FC4-mean', 'FCz-FC4-std', 'FCz-FC4-variance', 'Fz-C1', 'Fz-C1-mean', 'Fz-C1-std', 'Fz-C1-variance', 'Fz-C2', 'Fz-C2-mean', 'Fz-C2-std', 'Fz-C2-variance', 'Fz-C3', 'Fz-C3-mean', 'Fz-C3-std', 'Fz-C3-variance', 'Fz-C4', 'Fz-C4-mean', 'Fz-C4-std', 'Fz-C4-variance', 'Fz-CP1', 'Fz-CP1-mean', 'Fz-CP1-std', 'Fz-CP1-variance', 'Fz-CP2', 'Fz-CP2-mean', 'Fz-CP2-std', 'Fz-CP2-variance', 'Fz-CP3', 'Fz-CP3-mean', 'Fz-CP3-std', 'Fz-CP3-variance', 'Fz-CP4', 'Fz-CP4-mean', 'Fz-CP4-std', 'Fz-CP4-variance', 'Fz-CPz', 'Fz-CPz-mean', 'Fz-CPz-std', 'Fz-CPz-variance', 'Fz-FC1', 'Fz-FC1-mean', 'Fz-FC1-std', 'Fz-FC1-variance', 'Fz-FC2', 'Fz-FC2-mean', 'Fz-FC2-std', 'Fz-FC2-variance', 'Fz-FC3', 'Fz-FC3-mean', 'Fz-FC3-std', 'Fz-FC3-variance', 'Fz-FC4', 'Fz-FC4-mean', 'Fz-FC4-std', 'Fz-FC4-variance', 'Fz-FCz', 'Fz-FCz-mean', 'Fz-FCz-std', 'Fz-FCz-variance'};
trainedClassifier.ClassificationKNN = classificationKNN;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2022b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Fz-FC3-mean', 'Fz-FC3-std', 'Fz-FC3-variance', 'Fz-FC1-mean', 'Fz-FC1-std', 'Fz-FC1-variance', 'Fz-FCz-mean', 'Fz-FCz-std', 'Fz-FCz-variance', 'Fz-FC2-mean', 'Fz-FC2-std', 'Fz-FC2-variance', 'Fz-FC4-mean', 'Fz-FC4-std', 'Fz-FC4-variance', 'Fz-C3-mean', 'Fz-C3-std', 'Fz-C3-variance', 'Fz-C1-mean', 'Fz-C1-std', 'Fz-C1-variance', 'Fz-C2-mean', 'Fz-C2-std', 'Fz-C2-variance', 'Fz-C4-mean', 'Fz-C4-std', 'Fz-C4-variance', 'Fz-CP3-mean', 'Fz-CP3-std', 'Fz-CP3-variance', 'Fz-CP1-mean', 'Fz-CP1-std', 'Fz-CP1-variance', 'Fz-CPz-mean', 'Fz-CPz-std', 'Fz-CPz-variance', 'Fz-CP2-mean', 'Fz-CP2-std', 'Fz-CP2-variance', 'Fz-CP4-mean', 'Fz-CP4-std', 'Fz-CP4-variance', 'FC3-FC1-mean', 'FC3-FC1-std', 'FC3-FC1-variance', 'FC3-FCz-mean', 'FC3-FCz-std', 'FC3-FCz-variance', 'FC3-FC2-mean', 'FC3-FC2-std', 'FC3-FC2-variance', 'FC3-FC4-mean', 'FC3-FC4-std', 'FC3-FC4-variance', 'FC3-C3-mean', 'FC3-C3-std', 'FC3-C3-variance', 'FC3-C1-mean', 'FC3-C1-std', 'FC3-C1-variance', 'FC3-C2-mean', 'FC3-C2-std', 'FC3-C2-variance', 'FC3-C4-mean', 'FC3-C4-std', 'FC3-C4-variance', 'FC3-CP3-mean', 'FC3-CP3-std', 'FC3-CP3-variance', 'FC3-CP1-mean', 'FC3-CP1-std', 'FC3-CP1-variance', 'FC3-CPz-mean', 'FC3-CPz-std', 'FC3-CPz-variance', 'FC3-CP2-mean', 'FC3-CP2-std', 'FC3-CP2-variance', 'FC3-CP4-mean', 'FC3-CP4-std', 'FC3-CP4-variance', 'FC1-FCz-mean', 'FC1-FCz-std', 'FC1-FCz-variance', 'FC1-FC2-mean', 'FC1-FC2-std', 'FC1-FC2-variance', 'FC1-FC4-mean', 'FC1-FC4-std', 'FC1-FC4-variance', 'FC1-C3-mean', 'FC1-C3-std', 'FC1-C3-variance', 'FC1-C1-mean', 'FC1-C1-std', 'FC1-C1-variance', 'FC1-C2-mean', 'FC1-C2-std', 'FC1-C2-variance', 'FC1-C4-mean', 'FC1-C4-std', 'FC1-C4-variance', 'FC1-CP3-mean', 'FC1-CP3-std', 'FC1-CP3-variance', 'FC1-CP1-mean', 'FC1-CP1-std', 'FC1-CP1-variance', 'FC1-CPz-mean', 'FC1-CPz-std', 'FC1-CPz-variance', 'FC1-CP2-mean', 'FC1-CP2-std', 'FC1-CP2-variance', 'FC1-CP4-mean', 'FC1-CP4-std', 'FC1-CP4-variance', 'FCz-FC2-mean', 'FCz-FC2-std', 'FCz-FC2-variance', 'FCz-FC4-mean', 'FCz-FC4-std', 'FCz-FC4-variance', 'FCz-C3-mean', 'FCz-C3-std', 'FCz-C3-variance', 'FCz-C1-mean', 'FCz-C1-std', 'FCz-C1-variance', 'FCz-C2-mean', 'FCz-C2-std', 'FCz-C2-variance', 'FCz-C4-mean', 'FCz-C4-std', 'FCz-C4-variance', 'FCz-CP3-mean', 'FCz-CP3-std', 'FCz-CP3-variance', 'FCz-CP1-mean', 'FCz-CP1-std', 'FCz-CP1-variance', 'FCz-CPz-mean', 'FCz-CPz-std', 'FCz-CPz-variance', 'FCz-CP2-mean', 'FCz-CP2-std', 'FCz-CP2-variance', 'FCz-CP4-mean', 'FCz-CP4-std', 'FCz-CP4-variance', 'FC2-FC4-mean', 'FC2-FC4-std', 'FC2-FC4-variance', 'FC2-C3-mean', 'FC2-C3-std', 'FC2-C3-variance', 'FC2-C1-mean', 'FC2-C1-std', 'FC2-C1-variance', 'FC2-C2-mean', 'FC2-C2-std', 'FC2-C2-variance', 'FC2-C4-mean', 'FC2-C4-std', 'FC2-C4-variance', 'FC2-CP3-mean', 'FC2-CP3-std', 'FC2-CP3-variance', 'FC2-CP1-mean', 'FC2-CP1-std', 'FC2-CP1-variance', 'FC2-CPz-mean', 'FC2-CPz-std', 'FC2-CPz-variance', 'FC2-CP2-mean', 'FC2-CP2-std', 'FC2-CP2-variance', 'FC2-CP4-mean', 'FC2-CP4-std', 'FC2-CP4-variance', 'FC4-C3-mean', 'FC4-C3-std', 'FC4-C3-variance', 'FC4-C1-mean', 'FC4-C1-std', 'FC4-C1-variance', 'FC4-C2-mean', 'FC4-C2-std', 'FC4-C2-variance', 'FC4-C4-mean', 'FC4-C4-std', 'FC4-C4-variance', 'FC4-CP3-mean', 'FC4-CP3-std', 'FC4-CP3-variance', 'FC4-CP1-mean', 'FC4-CP1-std', 'FC4-CP1-variance', 'FC4-CPz-mean', 'FC4-CPz-std', 'FC4-CPz-variance', 'FC4-CP2-mean', 'FC4-CP2-std', 'FC4-CP2-variance', 'FC4-CP4-mean', 'FC4-CP4-std', 'FC4-CP4-variance', 'C3-C1-mean', 'C3-C1-std', 'C3-C1-variance', 'C3-C2-mean', 'C3-C2-std', 'C3-C2-variance', 'C3-C4-mean', 'C3-C4-std', 'C3-C4-variance', 'C3-CP3-mean', 'C3-CP3-std', 'C3-CP3-variance', 'C3-CP1-mean', 'C3-CP1-std', 'C3-CP1-variance', 'C3-CPz-mean', 'C3-CPz-std', 'C3-CPz-variance', 'C3-CP2-mean', 'C3-CP2-std', 'C3-CP2-variance', 'C3-CP4-mean', 'C3-CP4-std', 'C3-CP4-variance', 'C1-C2-mean', 'C1-C2-std', 'C1-C2-variance', 'C1-C4-mean', 'C1-C4-std', 'C1-C4-variance', 'C1-CP3-mean', 'C1-CP3-std', 'C1-CP3-variance', 'C1-CP1-mean', 'C1-CP1-std', 'C1-CP1-variance', 'C1-CPz-mean', 'C1-CPz-std', 'C1-CPz-variance', 'C1-CP2-mean', 'C1-CP2-std', 'C1-CP2-variance', 'C1-CP4-mean', 'C1-CP4-std', 'C1-CP4-variance', 'C2-C4-mean', 'C2-C4-std', 'C2-C4-variance', 'C2-CP3-mean', 'C2-CP3-std', 'C2-CP3-variance', 'C2-CP1-mean', 'C2-CP1-std', 'C2-CP1-variance', 'C2-CPz-mean', 'C2-CPz-std', 'C2-CPz-variance', 'C2-CP2-mean', 'C2-CP2-std', 'C2-CP2-variance', 'C2-CP4-mean', 'C2-CP4-std', 'C2-CP4-variance', 'C4-CP3-mean', 'C4-CP3-std', 'C4-CP3-variance', 'C4-CP1-mean', 'C4-CP1-std', 'C4-CP1-variance', 'C4-CPz-mean', 'C4-CPz-std', 'C4-CPz-variance', 'C4-CP2-mean', 'C4-CP2-std', 'C4-CP2-variance', 'C4-CP4-mean', 'C4-CP4-std', 'C4-CP4-variance', 'CP3-CP1-mean', 'CP3-CP1-std', 'CP3-CP1-variance', 'CP3-CPz-mean', 'CP3-CPz-std', 'CP3-CPz-variance', 'CP3-CP2-mean', 'CP3-CP2-std', 'CP3-CP2-variance', 'CP3-CP4-mean', 'CP3-CP4-std', 'CP3-CP4-variance', 'CP1-CPz-mean', 'CP1-CPz-std', 'CP1-CPz-variance', 'CP1-CP2-mean', 'CP1-CP2-std', 'CP1-CP2-variance', 'CP1-CP4-mean', 'CP1-CP4-std', 'CP1-CP4-variance', 'CPz-CP2-mean', 'CPz-CP2-std', 'CPz-CP2-variance', 'CPz-CP4-mean', 'CPz-CP4-std', 'CPz-CP4-variance', 'CP2-CP4-mean', 'CP2-CP4-std', 'CP2-CP4-variance', 'Fz-FC3', 'Fz-FC1', 'Fz-FCz', 'Fz-FC2', 'Fz-FC4', 'Fz-C3', 'Fz-C1', 'Fz-C2', 'Fz-C4', 'Fz-CP3', 'Fz-CP1', 'Fz-CPz', 'Fz-CP2', 'Fz-CP4', 'FC3-FC1', 'FC3-FCz', 'FC3-FC2', 'FC3-FC4', 'FC3-C3', 'FC3-C1', 'FC3-C2', 'FC3-C4', 'FC3-CP3', 'FC3-CP1', 'FC3-CPz', 'FC3-CP2', 'FC3-CP4', 'FC1-FCz', 'FC1-FC2', 'FC1-FC4', 'FC1-C3', 'FC1-C1', 'FC1-C2', 'FC1-C4', 'FC1-CP3', 'FC1-CP1', 'FC1-CPz', 'FC1-CP2', 'FC1-CP4', 'FCz-FC2', 'FCz-FC4', 'FCz-C3', 'FCz-C1', 'FCz-C2', 'FCz-C4', 'FCz-CP3', 'FCz-CP1', 'FCz-CPz', 'FCz-CP2', 'FCz-CP4', 'FC2-FC4', 'FC2-C3', 'FC2-C1', 'FC2-C2', 'FC2-C4', 'FC2-CP3', 'FC2-CP1', 'FC2-CPz', 'FC2-CP2', 'FC2-CP4', 'FC4-C3', 'FC4-C1', 'FC4-C2', 'FC4-C4', 'FC4-CP3', 'FC4-CP1', 'FC4-CPz', 'FC4-CP2', 'FC4-CP4', 'C3-C1', 'C3-C2', 'C3-C4', 'C3-CP3', 'C3-CP1', 'C3-CPz', 'C3-CP2', 'C3-CP4', 'C1-C2', 'C1-C4', 'C1-CP3', 'C1-CP1', 'C1-CPz', 'C1-CP2', 'C1-CP4', 'C2-C4', 'C2-CP3', 'C2-CP1', 'C2-CPz', 'C2-CP2', 'C2-CP4', 'C4-CP3', 'C4-CP1', 'C4-CPz', 'C4-CP2', 'C4-CP4', 'CP3-CP1', 'CP3-CPz', 'CP3-CP2', 'CP3-CP4', 'CP1-CPz', 'CP1-CP2', 'CP1-CP4', 'CPz-CP2', 'CPz-CP4', 'CP2-CP4'};
predictors = inputTable(:, predictorNames);
response = inputTable.Class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
KFolds = 10;
rng(1);
cvp = cvpartition(response, 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
numObservations = size(predictors, 1);
numClasses = 2;
validationScores = NaN(numObservations, numClasses);
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;

    % Feature Ranking and Selection
    % Replace Inf/-Inf values with NaN to prepare data for normalization
    trainingPredictors = standardizeMissing(trainingPredictors, {Inf, -Inf});
    % Normalize data for feature ranking
    predictorMatrix = normalize(trainingPredictors, "DataVariable", ~foldIsCategoricalPredictor);
    newPredictorMatrix = zeros(size(predictorMatrix));
    for i = 1:size(predictorMatrix, 2)
        if foldIsCategoricalPredictor(i)
            newPredictorMatrix(:,i) = grp2idx(predictorMatrix{:,i});
        else
            newPredictorMatrix(:,i) = predictorMatrix{:,i};
        end
    end
    predictorMatrix = newPredictorMatrix;
    responseVector = grp2idx(trainingResponse);

    % Rank features using ANOVA algorithm
    for i = 1:size(predictorMatrix, 2)
        pValues(i) = anova1(...
            predictorMatrix(:,i), ...
            responseVector, ...
            'off');
    end
    [~,featureIndex] = sort(-log(pValues), 'descend');
    numFeaturesToKeep = 50;
    includedPredictorNames = trainingPredictors.Properties.VariableNames(featureIndex(1:numFeaturesToKeep));
    trainingPredictors = trainingPredictors(:,includedPredictorNames);
    foldIsCategoricalPredictor = foldIsCategoricalPredictor(featureIndex(1:numFeaturesToKeep));

    % Train a classifier
    % This code specifies all the classifier options and trains the classifier.
    classificationKNN = fitcknn(...
        trainingPredictors, ...
        trainingResponse, ...
        'Distance', 'Cityblock', ...
        'Exponent', [], ...
        'NumNeighbors', 65, ...
        'DistanceWeight', 'Inverse', ...
        'Standardize', true, ...
        'ClassNames', [0; 1]);

    % Create the result struct with predict function
    featureSelectionFcn = @(x) x(:,includedPredictorNames);
    knnPredictFcn = @(x) predict(classificationKNN, x);
    validationPredictFcn = @(x) knnPredictFcn(featureSelectionFcn(x));

    % Add additional fields to the result struct

    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    [foldPredictions, foldScores] = validationPredictFcn(validationPredictors);

    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
    validationScores(cvp.test(fold), :) = foldScores;
end

% Compute validation accuracy
correctPredictions = (validationPredictions == response);
isMissing = isnan(response);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
